config/routes.rb
Rails.application.routes.draw do
  get 'users/:id/show', to: 'users#show', as: 'user_profile'
  devise_for :users
  root to: 'pages#home'
  resources :property_listings do
    resources :offers, only: [:new, :create]
  end

  resources :offers, only: [:show, :update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  belongs_to :property_listing
  validates :buyer_comment, length: { minimum: 50 }
end

app/models/property_listing.rb
class PropertyListing < ApplicationRecord
  belongs_to :user
  has_many :offers
  has_one_attached :image

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  include PgSearch::Model

  pg_search_scope :search_by_title_subtitle_and_description,
    against: [ :title, :sub_title, :description, :location ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :offers
  has_many :property_listings
  has_one_attached :avatar

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  ### Pundit
  # [...]
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  ### Devise
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
    end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)|(^offers$)/ || params[:controller] =~ /(^(rails_)?admin)|(^users$)/
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  def new
    @offer = Offer.new
    @property_listing = PropertyListing.find(params[:property_listing_id])
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user
    @property_listing = PropertyListing.find(params[:property_listing_id])
    @offer.property_listing = @property_listing

    if @offer.save
      redirect_to @property_listing, notice: "Your offer has been submitted!"
    else
      render :new
    end
  end

  def show
    @offer = Offer.find(params[:id])
  end

  def update
    @offer = Offer.find(params[:id])
    @offer.status = params["status"]
    @offer.save
    redirect_to @offer
  end

  private

  def offer_params
    params.require(:offer).permit(:offer_amount, :buyer_comment, :status, :seller_comment)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:home]

  def home
    @listings = PropertyListing.all.limit(6)
  end
end

app/controllers/property_listings_controller.rb
class PropertyListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update]
  skip_before_action :authenticate_user!, only: [:index, :show, :update]

  def index
    @scoped_listings = policy_scope(PropertyListing)

    @min_price = params[:min_price] == "" ? 1 : params[:min_price].to_i
    @max_price = params[:max_price].nil? ? nil : params[:max_price].to_i

    @filtered_listings = @scoped_listings.where(listing_price: 1..@max_price)

    if params[:query].present?
      @min_price = params[:min_price] == "" ? 1 : params[:min_price].to_i
      @max_price = params[:max_price].nil? ? nil : params[:max_price].to_i
      @filtered_listings = @scoped_listings.where(listing_price: @min_price..@max_price)
      @listings = @filtered_listings.search_by_title_subtitle_and_description(params[:query])
      authorize @listings
    else
      @listings = @scoped_listings
    end
  end

  def show
    @marker = [{
      lat: @property.latitude,
      lng: @property.longitude,
      info_window: render_to_string(partial: "info_window", locals: { property_listing: @property })
    }]

    @listings = PropertyListing.all.limit(3)
  end

  def new
    @property_listing = PropertyListing.new
    authorize @property_listing
  end

  def create
    @property_listing = PropertyListing.new(property_listing_params)
    @property_listing.user = current_user
    authorize @property_listing
    if @property_listing.save
      redirect_to property_listing_path(@property_listing)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @property.update(property_listing_params)
      redirect_to property_listing_path(@property)
    else
      render :edit
    end
  end

  private

  def set_listing
    @property = PropertyListing.find(params[:id])
    authorize @property
  end

  def property_listing_params
    params.require(:property_listing).permit(:title, :sub_title, :description,
                                             :location, :property_type, :listing_price, :number_of_bedrooms,
                                             :number_of_bathrooms, :number_of_parking_spaces, :property_size,
                                             :amenities, :year_built, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]

  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PropertyFinderClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <% unless (params[:controller] == "pages" && params[:action] == "home") || (params[:action] == "new") %>
      <div class="container">
    <% end %>
        
    <%= yield %>
        
    <% unless (params[:controller] == "pages" && params[:action] == "home") || (params[:action] == "new") %>
      </div>
    <% end %>

    <p class="notice m-0"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render 'shared/footer' %>


  </body>
</html>

app/views/offers/new.html.erb
<div class="form_banner">
  <div class="form-container">

    <h1 class="text-center mt-3">List your property</h1>

    <div class="property-listing-form">
      <%= simple_form_for [@property_listing, @offer] do |f| %>
        <%= f.input :offer_amount, placeholder: 'Enter amount in AED' %>
        <%= f.input :buyer_comment, label: "Notes" %>
        <%= f.submit class: 'btn btn-primary', value: "Submit your Offer" %>
      <% end %>
    </div>

  </div>
</div>

app/views/offers/show.html.erb
<h1>Offer From <%= @offer.user.first_name %></h1>
<p>for <%= link_to @offer.property_listing.title, property_listing_path(@offer.property_listing) %> </p>
<p><span class="status-<%= @offer.status %>"> <%= @offer.status %></span></p>
<p><%= @offer.user.first_name %> has offered <%= @offer.offer_amount %></p>

<hr>

<div class="box">
  <h2>Comment</h2>
  <p><%= @offer.buyer_comment %></p>

  <% if @offer.status == "pending" %>
    <%= link_to "Accept Offer", offer_path(@offer, status: 'accepted'), method: :patch, class:'btn btn-primary' %>
    <%= link_to "Decline Offer", offer_path(@offer, status: 'declined'), method: :patch, class:'btn btn-danger' %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <h1>Property Finder brings <strong>hassle free</strong> property buying <strong>to people of UAE</strong>!</h1>

    <p><b>Find Your Dream House Now!</b></p>

    <%#= link_to "Login", new_user_session_path, class: "btn btn-secondary btn-lg" %>
  </div>
</div>


<div class="container pt-3">

  <div class="square-cards">
    <% @listings.each do |listing| %>
      <!-- card -->
      <%= link_to property_listing_path(listing), class: "square-card-link" do %>
        <div class="square-card">
          <%= cl_image_tag listing.image.key %>
          <div class="card-text-information">
            <h2><%= truncate(listing.title, length: 60) %></h2>
            <p class="card-price"><%= number_with_delimiter(listing.listing_price.to_i) %> AED</p>
            <div class="card-key-information">
              <div>
                <i class="fas fa-street-view mr-3"></i>
                <p class="card-location">
                  <%= listing.location %>
                </p>
              </div>
              <div>
                <i class="far fa-calendar-alt"></i>
                <p>
                  <%= listing.year_built %>
                </p>
              </div>
              <div>
                <i class="fas fa-sink"></i>
                <p>
                  <%= listing.number_of_bathrooms %>
                </p>
              </div>
              <div>
                <i class="fas fa-bed"></i>
                <p>
                  <%= listing.number_of_bedrooms %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/property_listings/_info_window.html.erb
<h2><%= property_listing.title %></h2>
<p><%= property_listing.location %></p>

app/views/property_listings/edit.html.erb
<h1>Edit Property</h1>


<div class="property-listing-form">
      <%= simple_form_for @property do |f| %>
        <%= f.input :title %>
        <%= f.input :sub_title %>
        <%= f.input :description %>
        <%= f.input :location, class: 'address-field'%>
        <%= f.input :property_type %>
        <%= f.input :listing_price %>
        <div class="row text-center">
          <div class="col">
            <i class="fas fa-bed"></i>
            <%= f.input :number_of_bedrooms, collection: 1..10, label: false %>
          </div>
          <div class="col">
            <i class="fas fa-sink"></i>
            <%= f.input :number_of_bathrooms, collection: 1..12, label: false %>
          </div>
          <div class="col">
            <i class="fas fa-parking"></i>
            <%= f.input :number_of_parking_spaces, collection: 1..6, label: false %>
          </div>
        </div>
        <%= f.input :property_size %>
        <%= f.input :amenities %>
        <%= f.input :year_built %>
        <%= f.input :image, as: :file %>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>

app/views/property_listings/index.html.erb
<h1 class="mt-5">Search Properties</h1>

<%= form_tag property_listings_path, method: :get do%>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control mt-5",
    placeholder: "Find a property"
  %>

  <div class="mt-3">Price Filter</div>
  <%#= number_field_tag :min_price,
    params[:min_price],
    class: "form-control",
    placeholder: "Min Price"
  %>

  <%#= number_field_tag :max_price,
    params[:max_price],
    class: "form-control mt-2",
    placeholder: "Max Price"
  %>

  <%= submit_tag "Search", class: "btn btn-primary mt-2" %>
<% end %>


<div class="horizontal-cards">
  <% @listings.each do |listing| %>
    <!-- card -->
    <div class="horizontal-card">
     <!--  <div class="property-image" style="background-image: url('<%= cl_image_path listing.image.key %>')">
      </div> -->
      <%= cl_image_tag listing.image.key %>
      <div class="card-text-information">
        <h2><%= listing.title %></h2>
        <p><%= listing.description %></p>
        <p class="card-price"><%= number_with_delimiter(listing.listing_price.to_i,delimiter: ',') %> AED</p>
        <div class="card-key-information">
          <div>
            <i class="fas fa-street-view mr-3"></i>
            <p class="card-location">
              <%= listing.location %>
            </p>
          </div>
          <div>
            <i class="far fa-calendar-alt"></i>
            <p>
              <%= listing.year_built %>
            </p>
          </div>
          <div>
            <i class="fas fa-sink"></i>
            <p>
              <%= listing.number_of_bathrooms %>
            </p>
          </div>
          <div>
            <i class="fas fa-bed"></i>
            <p>
              <%= listing.number_of_bedrooms %>
            </p>
          </div>
        </div>
        <%= link_to property_listing_path(listing), class: "horizontal-card-arrow" do %>
          <i class="fas fa-arrow-circle-right"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<%#= raise %>

app/views/property_listings/new.html.erb
<div class="form_banner">
  <div class="form-container">

    <h1 class="text-center mt-3">List your property</h1>

    <div class="property-listing-form">
      <%= simple_form_for @property_listing do |f| %>
        <%= f.input :title %>
        <%= f.input :sub_title %>
        <%= f.input :description %>
        <%= f.input :location, class: 'address-field'%>
        <%= f.input :property_type %>
        <%= f.input :listing_price %>
        <div class="row text-center">
          <div class="col">
            <i class="fas fa-bed"></i>
            <%= f.input :number_of_bedrooms, collection: 1..10, label: false %>
          </div>
          <div class="col">
            <i class="fas fa-sink"></i>
            <%= f.input :number_of_bathrooms, collection: 1..12, label: false %>
          </div>
          <div class="col">
            <i class="fas fa-parking"></i>
            <%= f.input :number_of_parking_spaces, collection: 1..6, label: false %>
          </div>
        </div>
        <%= f.input :property_size %>
        <%= f.input :amenities %>
        <%= f.input :year_built %>
        <%= f.input :image, as: :file %>
        <%= f.submit class: 'btn btn-success' %>
      <% end %>
    </div>

  </div>
</div>

app/views/property_listings/show.html.erb
<div
  class="show-img"
  style="
    background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
    url('<%= cl_image_path @property.image.key %>')">

    <% if @property.user == current_user %>
      <%= link_to 'Edit Listing', edit_property_listing_path, class: 'btn btn-warning mt-3 ml-3' %>
    <% end %>
</div>

<%= link_to '< Go Back', 'javascript:history.back()', class: 'btn btn-outline-primary mt-3' %>


<% if @property.user != current_user %>
  <%= link_to 'Make An Offer', new_property_listing_offer_path(@property), class: 'btn btn-primary mt-3' %>
<% end %>


  <% if notice.present? %>
    <p class="notice py-3 mt-3 text-center"><%= notice %></p>
  <% end %>

<div class="container pt-3">
  <h1><%= @property.title %></h1>

  <p><%= @property.sub_title %></p>
  <p><%= "Seller: #{@property.user.first_name} #{@property.user.last_name}"%></p>

  <div class="my-2-col-grid">

    <div class="details">
      <p><i class="fas fa-building"></i> Property Type: <%= @property.property_type %></p>
      <p><i class="fas fa-bed"></i> <%= @property.number_of_bedrooms %></p>
      <p><i class="fas fa-bath"></i> <%= @property.number_of_bathrooms %></p>
      <p><i class="fas fa-ruler"></i> <%= @property.property_size %> </p>
      <p><i class="fas fa-car"></i> <%= @property.number_of_parking_spaces %> </p>
    </div>

    <div class="price">
      <p><i class="fas fa-dollar-sign"></i> <%= @property.listing_price %></p>
    </div>
  </div>

  <hr>


  <h2> Description</h2>

  <p><%= @property.description %></p>

  <hr>

  <div class="my-2-col-grid">
    <div class="amenities">
      <h2>Amenities</h2>
      <%= @property.amenities %>
    </div>
    <div class="location">
      <h2>Location</h2>
      <div> <%= @property.location %> </div>
      <div id="map"
         style="width: 400px; height: 200px;"
         data-markers="<%= @marker.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
      <div class="d-flex">long. <%= @property.longitude %> lat. <%= @property.latitude %></div>

    </div>
  </div>

  <hr>
  <h2>Properties Close By</h2>

  <div class="grid-3-col mt-3">
    <% @listings.each do |property| %>
      <%= link_to property_listing_path(property) do %>
        <div class="card-sm-sq">
          <div class="card-image" style="background-image: url('<%= cl_image_path property.image.key %>')"></div>
          <div class="card-content">
            <%= property.title %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>



  <p class="footer-address">Head Office:<br>
    Property Finder<br>
    knowledge Park<br>
    Dubai  TVQ03</p>




  <div class="footer-contact">
    Please contact: <br>
    <i class="far fa-envelope"></i><a href="mailto:propertyfinder@wagon.com"> propertyfinder@wagon.com</a><br>
    <i class="fas fa-phone-volume"></i><a href="tel:971040000">971 04 0000</a>
  </div>

  <div class="footer-copyright">
    <p>Copy Right <i class="fas fa-heart"></i> of Property Finder</p>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%=  image_tag image_path('logo.png') %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
          <%= link_to "Show all properties", property_listings_path, class: "nav-link" %>
        </li>
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Add Listing", new_property_listing_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://www.biography.com/.image/t_share/MTc5Mzk0NDcxNjk0MTgxNzA5/macho01_ba.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", user_profile_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @current_user.first_name %> <%= @current_user.last_name %></h1>
<% if current_user %>

<%= link_to 'Edit Profile', edit_user_registration_path(@current_user), class: 'btn btn-warning mb-3' %><br />
<%= cl_image_tag @current_user.avatar.key, class: 'user-image mb-5' %>

<!-- <hr> -->
<!-- <h2>Offers Given</h2> -->

<!-- <table class='offers-table'>
  <tr>
    <th>Property</th>
    <th>Offer Amount</th>
    <th>Status</th>
  </tr>
  <#% @current_user.offers.each do |offer| %>
    <tr>
      <td><%#= link_to offer.property_listing.title, offer_path(offer) %></td>
      <td><%#= offer.offer_amount %></td>
      <td><span class="status-<%#= offer.status %>"> <%#= offer.status %></span></td>
    </tr>
  <%# end %>
</table> -->

<hr>
<h2>Offers Received</h2>

  <table class='offers-table'>
    <tr>
      <th>Property</th>
      <th>Offer Amount</th>
      <th>Status</th>
    </tr>
    <% @current_user.property_listings.each do |property| %>
      <% property.offers.each do |offer| %>
        <tr class='offer-row'>
          <td><%= link_to offer.property_listing.title, offer_path(offer) %></td>
          <td><%= offer.offer_amount %></td>
          <td><span class="status-<%= offer.status %>"> <%= offer.status %></span></td>
        </tr>
      <% end %>
    <% end %>
  </table>

<hr>
<h2>Current Listings</h2>
<% end %>

<% @current_user.property_listings.each do |property| %>
  <%= link_to property_listing_path(property) do %>

    <div class="small-listing-card">

      <div class="listing-image" style="background-image: url('<%= cl_image_path property.image.key %>')"></div>
      <div class="card-content">
        <div class="card-title"><%= property.title %></div>
        <div>$<%= property.listing_price.to_i %></div>
        <div><i class="fas fa-map-marker-alt"></i> <%= property.location %></div>
      </div>
    </div>

  <% end %>
<% end %>